export const forest1To4 = [
    "1 giant owl",
    "1d4 cats",
    "2d4 woodcutters (commoners)",
    "1 badger or 1d4 poisonous snakes",
    "2d8 baboons",
    "1d6 + 3 hyenas",
    "1 owl",
    "1 pseudodragon",
    "1 panther",
    "1 giant poisonous snake",
    "1d6 + 2 boars",
    "1d4 + 1 giant lizards",
    "1 ape or 1 tiger",
    "2d6 tribal warriors with 1d6 mastiffs",
    "1d6 + 2 giant bats or 3d6 flying snakes",
    "1 scout or 2d4 guards with 1d8 mastiffs",
    "1d8 + 1 winged kobolds",
    "1d10 + 5 giant rats or 2d6 + 3 giant weasels",
    "1d4 +1 needle blights with 1d6 + 3 twig blights",
    "A lost, weeping child. If the characters take the child home, the parents reward them with 1d3 potions of healing."
];

export const forest5To10 = [
    "2d4 vine blights",
    "2d6 hobgoblins or 2d6 orcs",
    "2d4 apes or 2d4 satyrs",
    "1d3 will-o'-wisps",
    "1d4 swarms of poisonous snakes",
    "1 orc Eye of Gruumsh with 1d3 orogs and 1d8 + 2 orcs",
    "1d3 constrictor snakes or 1d4 tigers",
    "1 goblin boss with 3d6 goblins",
    "1 faerie dragon (any age)",
    "1 brown bear or 1d6 + 2 black bears",
    "1d4 giant boards",
    "1d8 + 1 giant spiders",
    "1 lizardfolk shaman with 2d4 lizardfolk",
    "1d10 giant toads",
    "1d4 ankhegs",
    "1d3 awakened trees (day) or 1 banshee (night)",
    "A small shack almost hidden by the deep forest. The interior is empty aside from a large cast-iron oven.",
    "1 couatl",
    "1d4 ogres or 1d6 + 2 half-ogres",
    "1d6 wererates"
];

export const grassland1To5 = [
    "1 hobgolblin captain with 1d4 + 1 hobgoblins",
    "1 chimera",
    "1 gorgon",
    "1d2 couatls",
    "1 ankylosaurus",
    "1 weretiger",
    "1d3 allosauruses",
    "1d3 elephants",
    "A circle of standing stones within which the air is utterly still, no matter how hard the wind blows outside.",
    "1 phase spider",
    "1 gnoll pack lord with 1d4 giant hyenas",
    "1 orog or 1 pegasus",
    "1 ankheg",
    "1d3 rhinoceroses",
    "1d3 cockatrices",
    "1d6 + 2 giant wasps or 1d4 + 3 swarms of insects",
    "1d4 jackalweres or 1d4 scouts",
    "1d8 giant goats or 1d8 worgs",
    "2d4 hobgoblins, 2d4 orcs, or 2d4 gnolls",
    "2d4 goblins"
];

export const grassland6To10 = [
    "1d3 gorgons",
    "1d4 cyclopes",
    "1d3 gnoll fangs of Yeenoghu",
    "1 chimera",
    "1d4 + 1 veterans riding horses",
    "A tornado that touches down 1d6 miles away, tearing up the land for 1 mile before it dissipates",
    "1d3 manticores",
    "2d4 ankhegs",
    "1d8 + 1 centaurs",
    "1d6 + 2 griffons",
    "1d6 elephants",
    "A stretch of land littered with rotting war machines, bones, and banners of forgotten armies",
    "1d8 + 1 bugbears",
    "1 gnoll pack lord with 1d4 + 1 giant hyenas",
    "2d4 scarecrows",
    "1d12 lions",
    "1d10 thri-kreen",
    "1 allosaurus",
    "1 tiger",
    "1d2 giant eagles or 1d2 giant vultures"
];

export const arctic1To4 = [
    "1 giant owl",
    "1d6 + 3 kobolds",
    "1d4 + 3 trappers (commoners)",
    "1 owl",
    "2d4 blood hawks",
    "2d6 bandits",
    "1d3 winged kobolds with 1d6 kobolds",
    "The partially eaten carcass of a mammoth, from which 1d4 weeks of rations can be harvested",
    "2d8 hunters (tribal warriors",
    "1 half-ogre",
    "Single-file tracks in the snow that stop abruptly",
    "1d3 ice mephites",
    "1 brown bear",
    "1d6 + 1 orcs",
    "1 polar bear",
    "1d6 scouts",
    "1 saber-toothed tiger",
    "A frozen pond with a jagged hole in the ice that appears recently made",
    "1 berserker",
    "1 griffon"
];

export const arctic5To10 = [
    "2 saber-toothed tigers",
    "1d4 half-ogres",
    "1d3 + 1 brown bears",
    "1d3 polar bears",
    "2d4 berserkers",
    "A half-orc druid tending to an injured polar bear. If the characters assist the druid, she gives them a vial of antitoxin.",
    "2d8 scouts",
    "2d4 ice mephits",
    "2d6 +1 zombies aboard a galleon trapped in the ice. Searching the ship yields 2d20 days of rations.",
    "1 manticore",
    "2d6 + 3 orcs",
    "1d6 + 2 ogres",
    "2d4 griffons",
    "1d4 veterans",
    "1 bandit captain with 1 druid, 1d3 berserkers, and 2d10 + 5 bandits",
    "1d4 hours of extreme cold (see chapter 5 of the Dungeon Master's Guide)",
    "1 young remorhaz",
    "1 orc Eye of Gruumsh with 1d6 orogs and 2d8 + 6 orcs",
    "1 revenant",
    "A howl that echoes over the land for 1d3 minutes"
];